services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Your_password123!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - appnetwork

  patientapi:
    build:
      context: ./Back
      dockerfile: Dockerfile
    container_name: patientapi
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=PatientDB;User Id=sa;Password=Your_password123!;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    networks:
      - appnetwork

  authapi:
    build:
      context: ./AuthApi
      dockerfile: Dockerfile
    container_name: authapi
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=AuthDB;User Id=sa;Password=Your_password123!;TrustServerCertificate=True;
    ports:
      - "5001:8080"
    networks:
      - appnetwork

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - patientapi
      - authapi
    environment:
      - PATIENT_API_URL=http://patientapi:8080/api
      - AUTH_API_URL=http://authapi:8080/api
    ports:
      - "5002:8080"
    networks:
      - appnetwork

volumes:
  sql_data:

networks:
  appnetwork:
