services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Kyn(JY2f59{!
    ports:
      - "1433:1433"
    networks:
      - backend

  api:
    build: ./AuthApi
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=UserDatabase;User Id=sa;Password=Kyn(JY2f59{!;
    ports:
      - "5000:80"
    networks:
      - backend

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  gateway:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    ports:
      - "7001:8080"
      - "7000:8081"

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "8001:8080"
      - "8000:8081"

networks:
  backend:
