version: "3.9"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  auth_api:
    build:
      context: ./AuthApi
      dockerfile: Dockerfile
    ports:
      - "6000:8080"
      - "6001:8081"
    networks:
      - test

networks:
  test:
    name: test
    driver: bridge
