services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=Your_password123!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - appnetwork

  webapi:
    build:
      context: ./Back
      dockerfile: Dockerfile
    container_name: patientapi
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=PatientDB;User Id=sa;Password=Your_password123!;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    networks:
      - appnetwork

volumes:
  sql_data:

networks:
  appnetwork:
