services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - appnetwork

  authapi:
    build:
      context: ./AuthApi
      dockerfile: Dockerfile
    container_name: authapi
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=AuthDB;User Id=SA;Password=${SA_PASSWORD};TrustServerCertificate=True;"
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
    ports:
      - "5001:8080"
    networks:
      - appnetwork

  patientapi:
    build:
      context: ./Back
      dockerfile: Dockerfile
    container_name: patientapi
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=PatientDB;User Id=SA;Password=${SA_PASSWORD};TrustServerCertificate=True;"
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: ${JWT_ISSUER}
      Jwt__Audience: ${JWT_AUDIENCE}
    ports:
      - "5000:8080"
    networks:
      - appnetwork

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - patientapi
      - authapi
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      URL__PATIENT_API: "http://patientapi:8080/api"
      URL__AUTH_API: "http://authapi:8080/api"
    ports:
      - "5002:8080"
    networks:
      - appnetwork

  gateway:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    container_name: gateway
    depends_on:
      - frontend
      - patientapi
      - authapi
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5003:8080"
    networks:
      - appnetwork

volumes:
  sql_data:

networks:
  appnetwork:
